import { StyleSheet, Platform } from 'react-native';

export const theme = {
  colors: {
    background: '#0A0A0A',
    surface: '#1A1A1A',
    surfaceBright: '#3a3939',
    surfaceContainerLowest: '#0e0e0e',
    surfaceContainerLow: '#1c1b1b',
    surfaceContainer: '#201f1f',
    surfaceContainerHigh: '#2a2a2a',
    surfaceContainerHighest: '#353534',
    onSurface: '#e5e2e1',
    onSurfaceVariant: '#d0c4bc',
    inverseSurface: '#e5e2e1',
    inverseOnSurface: '#313030',
    outline: '#998f87',
    outlineVariant: '#4d453f',
    surfaceTint: '#d3c4b8',
    primary: '#f1e1d4',
    onPrimary: '#382f26',
    primaryContainer: '#d4c5b9',
    onPrimaryContainer: '#5c5148',
    inversePrimary: '#685c53',
    secondary: '#c6c6c6',
    onSecondary: '#2f3131',
    secondaryContainer: '#454747',
    onSecondaryContainer: '#b5b5b5',
    tertiary: '#dfe4e8',
    onTertiary: '#2c3134',
    tertiaryContainer: '#c3c8cc',
    onTertiaryContainer: '#4e5457',
    error: '#ffb4ab',
    onError: '#690005',
    errorContainer: '#93000a',
    onErrorContainer: '#ffdad6',
    primaryFixed: '#f0e0d3',
    primaryFixedDim: '#d3c4b8',
    onPrimaryFixed: '#221a13',
    onPrimaryFixedVariant: '#4f453c',
    secondaryFixed: '#e2e2e2',
    secondaryFixedDim: '#c6c6c6',
    onSecondaryFixed: '#1a1c1c',
    onSecondaryFixedVariant: '#454747',
    tertiaryFixed: '#dee3e7',
    tertiaryFixedDim: '#c2c7cb',
    onTertiaryFixed: '#171c1f',
    onTertiaryFixedVariant: '#42474b',
  },
  fonts: {
    headline: 'PlayfairDisplay_400Regular',
    body: 'Inter_400Regular',
    medium: 'Inter_500Medium',
    semibold: 'Inter_600SemiBold',
  },
  rounded: {
    soft: 4,
  },
};

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  card: {
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    borderRadius: theme.rounded.soft,
    padding: 24,
  },
  headline: {
    fontFamily: theme.fonts.headline,
    fontSize: 32,
    color: theme.colors.primaryContainer,
    textAlign: 'center',
    marginBottom: 8,
  },
  divider: {
    height: 1,
    backgroundColor: '#2A2A2A',
    marginVertical: 16,
  },
});
