import { StyleSheet } from 'react-native';

export const theme = {
  colors: {
    background: '#181715',
    surface: '#22201d',
    surfaceBright: '#38342f',
    surfaceContainerLowest: '#1b1a18',
    surfaceContainerLow: '#201f1c',
    surfaceContainer: '#24221f',
    surfaceContainerHigh: '#2d2a26',
    surfaceContainerHighest: '#38342f',
    onSurface: '#eee5dc',
    onSurfaceVariant: '#cfc4b8',
    inverseSurface: '#eee5dc',
    inverseOnSurface: '#29251f',
    outline: '#81766b',
    outlineVariant: '#3b3630',
    border: '#36322d',
    mutedBorder: '#2e2a26',
    primary: '#ead8c8',
    onPrimary: '#2c241d',
    primaryContainer: '#d6c4b5',
    onPrimaryContainer: '#4d433a',
    secondary: '#bdb5ad',
    onSecondary: '#2f2b27',
    secondaryContainer: '#38342f',
    onSecondaryContainer: '#d9d0c7',
    success: '#8fcf9a',
    successContainer: '#1f3325',
    warning: '#e2bd72',
    warningContainer: '#3a2d18',
    error: '#ffb4ab',
    onError: '#690005',
    errorContainer: '#4a1d1d',
    onErrorContainer: '#ffdad6',

    // Compatibility keys
    surfaceTint: '#ead8c8',
    tertiary: '#bdb5ad',
    onTertiary: '#2f2b27',
    tertiaryContainer: '#38342f',
    onTertiaryContainer: '#d9d0c7',
    primaryFixed: '#ead8c8',
    primaryFixedDim: '#d6c4b5',
    onPrimaryFixed: '#2c241d',
    onPrimaryFixedVariant: '#4d433a',
    secondaryFixed: '#bdb5ad',
    secondaryFixedDim: '#bdb5ad',
    onSecondaryFixed: '#2f2b27',
    onSecondaryFixedVariant: '#38342f',
    tertiaryFixed: '#bdb5ad',
    tertiaryFixedDim: '#bdb5ad',
    onTertiaryFixed: '#2f2b27',
    onTertiaryFixedVariant: '#38342f',
  },
  fonts: {
    headline: 'PlayfairDisplay_400Regular',
    body: 'Inter_400Regular',
    medium: 'Inter_500Medium',
    semibold: 'Inter_600SemiBold',
  },
  rounded: {
    soft: 4,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
  },
  radii: {
    xs: 4,
    sm: 6,
    md: 8,
    lg: 12,
  },
  typography: {
    labelLetterSpacing: 1.5,
    sectionLabelSize: 11,
    bodySize: 15,
    bodyLineHeight: 22,
  }
};

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  card: {
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: theme.radii.xs,
    padding: theme.spacing.xl,
  },
  headline: {
    fontFamily: theme.fonts.headline,
    fontSize: 32,
    color: theme.colors.primary,
    textAlign: 'center',
    marginBottom: theme.spacing.sm,
  },
  divider: {
    height: 1,
    backgroundColor: theme.colors.border,
    marginVertical: theme.spacing.lg,
  },
});

